/* eslint-disable */
/**
 * Generated `api` utility.
 *
 * THIS CODE IS AUTOMATICALLY GENERATED.
 *
 * Generated by convex@1.11.2.
 * To regenerate, run `npx convex dev`.
 * @module
 */

import type {
  ApiFromModules,
  FilterApi,
  FunctionReference,
} from "convex/server";
import type * as functions_contents from "../functions/contents.js";
import type * as functions_invites from "../functions/invites.js";
import type * as functions_members from "../functions/members.js";
import type * as functions_teams from "../functions/teams.js";
import type * as functions_topics from "../functions/topics.js";
import type * as functions_users from "../functions/users.js";

/**
 * A utility for referencing Convex functions in your app's API.
 *
 * Usage:
 * ```js
 * const myFunctionReference = api.myModule.myFunction;
 * ```
 */
declare const fullApi: ApiFromModules<{
  "functions/contents": typeof functions_contents;
  "functions/invites": typeof functions_invites;
  "functions/members": typeof functions_members;
  "functions/teams": typeof functions_teams;
  "functions/topics": typeof functions_topics;
  "functions/users": typeof functions_users;
}>;
export declare const api: FilterApi<
  typeof fullApi,
  FunctionReference<any, "public">
>;
export declare const internal: FilterApi<
  typeof fullApi,
  FunctionReference<any, "internal">
>;
